<a href="https://colab.research.google.com/github/vijithan/6AMBatch-Oct/blob/master/Copy_of_TensorFlow_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting started with TensorFlow: A guide to the fundamentals

## What is Tensorflow:
- Open-source machine learning python library used to model data, preprocess the data and serve models.

## Why use TensorFlow
- Because it contains most of the common machine learning functions we are going to use.

## Coverage
  - Introduction to tensors (Creating tensors)
  - Getting information from tensors (Attributes)
  - Manipulating tensors
  - Tensors and numpy
  - Using @tf.function (A way to speed your regular python functions)
  - Using GPU's with Tensorflow
  

In [ ]:
# Create a timestamp
import datetime

print(f"Notebook last run (end-to-end: {datetime.datetime.now()})")

Notebook last run (end-to-end: 2024-05-27 00:56:04.203260)


In [ ]:
! pip install tensorflow

In [ ]:
# Import the tensorflow
import tensorflow as tf

In [ ]:
#check the version of the tensorflow
print(tf.__version__)

2.15.0


### Creating tensors with tf.constant()

In [ ]:
# Create a tensor scalar of rank 0
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimnesions in the tensor
scalar.ndim

0

In [ ]:
# Create a vector with more than 0 dimensions
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# get dimension
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7,  5]], dtype=int32)>

In [ ]:
# GEt the dimension
matrix.ndim

2

In [ ]:
# Matrix of a float
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]])

In [ ]:
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float32)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor of rank 3
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

### Creating tensor with `tf.Variable()`

In [ ]:
# Create a same tensor with tf.Variable and tf.constant
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Change one of th elements is teh changeable tensor
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
# WOnt error
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# WIll error
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'